-- =====================================================================
-- QUYỀN TRUY CẬP — đặt đúng như DB thật (SINH TỰ ĐỘNG bởi scripts/db/sinh-quyen-truy-cap.mjs, 30/09/2026)
--
-- Nguồn: ACL thật đọc chỉ-đọc từ DB Nhân sự (naglcxbpxnntiglrzeqx) và Tài chính (eodrpyedatohsovobsxj).
-- Lý do: project Supabase mới tự cấp ALL cho anon/authenticated trên bảng mới; pg_restore không thu hồi
-- → bản thử lỏng hơn thật. File này THU HỒI rồi CẤP LẠI đúng như nguồn. Chạy lại nhiều lần được.
-- KHÔNG thêm/bớt quyền so với 2 DB thật (Tài chính vẫn cấp đủ quyền bảng cho authenticated như hiện tại,
-- RLS là lớp chặn) — siết thêm là việc riêng, phải được chủ dự án duyệt.
-- =====================================================================

-- Bảng tạo mới trong public KHÔNG tự cấp gì cho anon/authenticated (như Nhân sự đã siết từ 10/08).
alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated;


-- ---- Bảng / view / sequence: Nhân sự ----
revoke all on table public.allowance_types from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE on table public.allowance_types to authenticated;
revoke all on table public.app_users from anon, authenticated;
grant SELECT, MAINTAIN on table public.app_users to authenticated;
revoke all on table public.attendance_days from anon, authenticated;
grant INSERT, SELECT, UPDATE, MAINTAIN on table public.attendance_days to authenticated;
revoke all on table public.attendance_logs from anon, authenticated;
grant SELECT, MAINTAIN on table public.attendance_logs to authenticated;
revoke all on table public.bang_thanh_toan_to from anon, authenticated;
grant SELECT, UPDATE, DELETE on table public.bang_thanh_toan_to to authenticated;
revoke all on table public.ca_cong_nhat from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE on table public.ca_cong_nhat to authenticated;
revoke all on table public.cfg_base_salary from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.cfg_base_salary to authenticated;
revoke all on table public.cfg_insurance_rates from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.cfg_insurance_rates to authenticated;
revoke all on table public.cfg_overtime_rates from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.cfg_overtime_rates to authenticated;
revoke all on table public.cfg_pit_brackets from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.cfg_pit_brackets to authenticated;
revoke all on table public.cfg_pit_deductions from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.cfg_pit_deductions to authenticated;
revoke all on table public.cfg_region_min_wage from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.cfg_region_min_wage to authenticated;
revoke all on table public.cham_cong_cong_nhat from anon, authenticated;
grant SELECT on table public.cham_cong_cong_nhat to authenticated;
revoke all on table public.chung_tu from anon, authenticated;
grant SELECT on table public.chung_tu to authenticated;
revoke all on table public.chung_tu_con_thieu from anon, authenticated;
grant SELECT on table public.chung_tu_con_thieu to authenticated;
revoke all on sequence public.chung_tu_so_hieu_seq from anon, authenticated;
revoke all on table public.companies from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE on table public.companies to authenticated;
revoke all on table public.departments from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, MAINTAIN on table public.departments to authenticated;
revoke all on table public.dependents from anon, authenticated;
grant INSERT, SELECT, UPDATE, MAINTAIN on table public.dependents to authenticated;
revoke all on table public.dong_thanh_toan_to from anon, authenticated;
grant SELECT on table public.dong_thanh_toan_to to authenticated;
revoke all on table public.employee_documents from anon, authenticated;
grant INSERT, SELECT, UPDATE, MAINTAIN on table public.employee_documents to authenticated;
revoke all on table public.employee_sensitive from anon, authenticated;
grant INSERT, SELECT, UPDATE, MAINTAIN on table public.employee_sensitive to authenticated;
revoke all on table public.employees from anon, authenticated;
grant INSERT, SELECT, UPDATE, MAINTAIN on table public.employees to authenticated;
revoke all on table public.labor_contracts from anon, authenticated;
grant INSERT, SELECT, UPDATE, MAINTAIN on table public.labor_contracts to authenticated;
revoke all on table public.muc_luong_hop_dong from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.muc_luong_hop_dong to authenticated;
revoke all on table public.nhan_vien_chuc_danh from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.nhan_vien_chuc_danh to authenticated;
revoke all on table public.payroll_periods from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.payroll_periods to authenticated;
revoke all on table public.payslip_items from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.payslip_items to authenticated;
revoke all on table public.payslips from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.payslips to authenticated;
revoke all on table public.phien_cham_cong_to from anon, authenticated;
grant SELECT on table public.phien_cham_cong_to to authenticated;
revoke all on table public.position_allowances from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE on table public.position_allowances to authenticated;
revoke all on table public.positions from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, MAINTAIN on table public.positions to authenticated;
revoke all on table public.sua_chua_cong from anon, authenticated;
grant SELECT on table public.sua_chua_cong to authenticated;
revoke all on table public.sua_tay_bang_thanh_toan from anon, authenticated;
grant SELECT on table public.sua_tay_bang_thanh_toan to authenticated;
revoke all on table public.to_doi from anon, authenticated;
grant INSERT, SELECT on table public.to_doi to authenticated;
revoke all on table public.to_doi_nguoi_cham from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE on table public.to_doi_nguoi_cham to authenticated;
revoke all on table public.to_doi_thanh_vien from anon, authenticated;
grant INSERT, SELECT, UPDATE on table public.to_doi_thanh_vien to authenticated;
revoke all on table public.truy_linh_luong from anon, authenticated;
grant SELECT on table public.truy_linh_luong to authenticated;
revoke all on table public.work_shifts from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, MAINTAIN on table public.work_shifts to authenticated;

-- ---- Quyền theo cột: Nhân sự ----
grant INSERT (ngoai_gio_tu), UPDATE (ngoai_gio_tu) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ngoai_gio_den), UPDATE (ngoai_gio_den) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ca_sang_tu), UPDATE (ca_sang_tu) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ca_sang_den), UPDATE (ca_sang_den) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ca_chieu_tu), UPDATE (ca_chieu_tu) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ca_chieu_den), UPDATE (ca_chieu_den) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ca_toi_tu), UPDATE (ca_toi_tu) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ca_toi_den), UPDATE (ca_toi_den) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (thuong), SELECT (thuong), UPDATE (thuong) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (thuong_ly_do), SELECT (thuong_ly_do), UPDATE (thuong_ly_do) on public.cham_cong_cong_nhat to authenticated;
grant SELECT (thuong) on public.dong_thanh_toan_to to authenticated;
grant SELECT (thanh_tien) on public.dong_thanh_toan_to to authenticated;
grant INSERT (quan_ly_to_doi), UPDATE (quan_ly_to_doi) on public.app_users to authenticated;
grant UPDATE (da_xac_nhan) on public.attendance_logs to authenticated;
grant UPDATE (xac_nhan_boi) on public.attendance_logs to authenticated;
grant UPDATE (xac_nhan_luc) on public.attendance_logs to authenticated;
grant UPDATE (ghi_chu_xac_nhan) on public.attendance_logs to authenticated;
grant UPDATE (name) on public.to_doi to authenticated;
grant UPDATE (department_id) on public.to_doi to authenticated;
grant UPDATE (to_truong_id) on public.to_doi to authenticated;
grant UPDATE (ghi_chu) on public.to_doi to authenticated;
grant UPDATE (is_active) on public.to_doi to authenticated;
grant INSERT (to_doi_id) on public.phien_cham_cong_to to authenticated;
grant INSERT (work_date) on public.phien_cham_cong_to to authenticated;
grant INSERT (nguoi_cham_id) on public.phien_cham_cong_to to authenticated;
grant INSERT (ghi_chu), UPDATE (ghi_chu) on public.phien_cham_cong_to to authenticated;
grant UPDATE (da_duyet) on public.phien_cham_cong_to to authenticated;
grant UPDATE (duyet_boi) on public.phien_cham_cong_to to authenticated;
grant UPDATE (duyet_luc) on public.phien_cham_cong_to to authenticated;
grant INSERT (phien_id) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (work_date) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (employee_id) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (ghi_chu), UPDATE (ghi_chu) on public.cham_cong_cong_nhat to authenticated;
grant INSERT (id), UPDATE (id) on public.app_users to authenticated;
grant INSERT (full_name), UPDATE (full_name) on public.app_users to authenticated;
grant INSERT (role), UPDATE (role) on public.app_users to authenticated;
grant INSERT (employee_id), UPDATE (employee_id) on public.app_users to authenticated;
grant INSERT (is_active), UPDATE (is_active) on public.app_users to authenticated;
grant INSERT (created_at), UPDATE (created_at) on public.app_users to authenticated;
grant INSERT (updated_at), UPDATE (updated_at) on public.app_users to authenticated;
grant INSERT (tabs), UPDATE (tabs) on public.app_users to authenticated;
grant INSERT (duyet_cong), SELECT (duyet_cong), UPDATE (duyet_cong) on public.app_users to authenticated;

-- ---- Bảng / view / sequence: Tài chính ----
revoke all on table public.bu_cong_no_am from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.bu_cong_no_am to authenticated;
revoke all on table public.but_toan_quy_cong_truong from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.but_toan_quy_cong_truong to authenticated;
revoke all on table public.cau_hinh_he_thong from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cau_hinh_he_thong to authenticated;
revoke all on table public.chi_tiet_lan_tra from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.chi_tiet_lan_tra to authenticated;
revoke all on table public.chung_tu_fmb from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.chung_tu_fmb to authenticated;
revoke all on table public.chuyen_quy from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.chuyen_quy to authenticated;
revoke all on table public.cong_ty from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cong_ty to authenticated;
revoke all on table public.de_nghi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.de_nghi to authenticated;
revoke all on table public.doi_tuong_vay from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.doi_tuong_vay to authenticated;
revoke all on table public.dot_duyet from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.dot_duyet to authenticated;
revoke all on table public.du_an from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.du_an to authenticated;
revoke all on table public.giao_dich_da_huy from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.giao_dich_da_huy to authenticated;
revoke all on table public.giao_dich_lich_su from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.giao_dich_lich_su to authenticated;
revoke all on table public.khach_hang from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.khach_hang to authenticated;
revoke all on table public.khoan_muc_chi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.khoan_muc_chi to authenticated;
revoke all on table public.khoan_muc_thu from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.khoan_muc_thu to authenticated;
revoke all on table public.lan_tra_tien from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.lan_tra_tien to authenticated;
revoke all on table public.menu_nhan_vien from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.menu_nhan_vien to authenticated;
revoke all on table public.muc_de_nghi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.muc_de_nghi to authenticated;
revoke all on table public.ngan_sach from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.ngan_sach to authenticated;
revoke all on table public.nguon_tien_nhan_vien from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.nguon_tien_nhan_vien to authenticated;
revoke all on table public.nha_cung_cap from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.nha_cung_cap to authenticated;
revoke all on table public.nhan_vien from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.nhan_vien to authenticated;
revoke all on table public.nhan_vien_nhay_cam from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.nhan_vien_nhay_cam to authenticated;
revoke all on table public.nhat_ky from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.nhat_ky to authenticated;
revoke all on table public.phieu_thu from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.phieu_thu to authenticated;
revoke all on table public.quy_tien_mat from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.quy_tien_mat to authenticated;
revoke all on table public.so_thu_tu_de_nghi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.so_thu_tu_de_nghi to authenticated;
revoke all on table public.tai_khoan_ngan_hang from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.tai_khoan_ngan_hang to authenticated;
revoke all on table public.ton_dau_ky from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.ton_dau_ky to authenticated;
revoke all on table public.v_chi_phi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_chi_phi to authenticated;
revoke all on table public.v_cho_toi_xu_ly from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_cho_toi_xu_ly to authenticated;
revoke all on table public.v_cong_no_phai_tra from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_cong_no_phai_tra to authenticated;
revoke all on table public.v_cong_no_tam_ung from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_cong_no_tam_ung to authenticated;
revoke all on table public.v_cong_no_tam_ung_theo_nguoi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_cong_no_tam_ung_theo_nguoi to authenticated;
revoke all on table public.v_cong_no_vay from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_cong_no_vay to authenticated;
revoke all on table public.v_de_nghi_trong_pham_vi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_de_nghi_trong_pham_vi to authenticated;
revoke all on table public.v_dot_can_chi from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_dot_can_chi to authenticated;
revoke all on table public.v_dot_duyet_tong_hop from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_dot_duyet_tong_hop to authenticated;
revoke all on table public.v_giao_dich_vay from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_giao_dich_vay to authenticated;
revoke all on table public.v_khoan_am_cho_bu from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_khoan_am_cho_bu to authenticated;
revoke all on table public.v_muc_tong_hop from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_muc_tong_hop to authenticated;
revoke all on table public.v_ngan_sach from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_ngan_sach to authenticated;
revoke all on table public.v_nhap_quy_trung from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_nhap_quy_trung to authenticated;
revoke all on table public.v_quy_chung_chi_ho from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_quy_chung_chi_ho to authenticated;
revoke all on table public.v_quy_tien_mat_theo_khoan_muc from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_quy_tien_mat_theo_khoan_muc to authenticated;
revoke all on table public.v_so_du_nguon_tien from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_so_du_nguon_tien to authenticated;
revoke all on table public.v_so_du_quy_ca_nhan from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_so_du_quy_ca_nhan to authenticated;
revoke all on table public.v_so_quy from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_so_quy to authenticated;
revoke all on table public.v_so_quy_luy_ke from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_so_quy_luy_ke to authenticated;
revoke all on table public.v_tam_ung_con_giu from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.v_tam_ung_con_giu to authenticated;
revoke all on table public.vai_tro_nhan_vien from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.vai_tro_nhan_vien to authenticated;

-- ---- Hàm: Nhân sự ----
revoke all on function public.bao_cao_luong_theo_ky(uuid,integer,integer) from public, anon, authenticated;
grant execute on function public.bao_cao_luong_theo_ky(uuid,integer,integer) to authenticated;
revoke all on function public.bao_cao_luong_theo_nhan_vien(uuid,integer,integer) from public, anon, authenticated;
grant execute on function public.bao_cao_luong_theo_nhan_vien(uuid,integer,integer) to authenticated;
revoke all on function public.bon_khoang_chong_nhau(time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone) from public, anon, authenticated;
grant execute on function public.bon_khoang_chong_nhau(time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone) to public;
grant execute on function public.bon_khoang_chong_nhau(time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone) to anon;
grant execute on function public.bon_khoang_chong_nhau(time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone) to authenticated;
revoke all on function public.can_manage_attendance() from public, anon, authenticated;
grant execute on function public.can_manage_attendance() to public;
grant execute on function public.can_manage_attendance() to authenticated;
revoke all on function public.can_manage_payroll() from public, anon, authenticated;
grant execute on function public.can_manage_payroll() to public;
grant execute on function public.can_manage_payroll() to authenticated;
revoke all on function public.can_read_all_employees() from public, anon, authenticated;
grant execute on function public.can_read_all_employees() to public;
grant execute on function public.can_read_all_employees() to authenticated;
revoke all on function public.can_read_attendance_of(uuid) from public, anon, authenticated;
grant execute on function public.can_read_attendance_of(uuid) to public;
grant execute on function public.can_read_attendance_of(uuid) to authenticated;
revoke all on function public.can_read_payroll() from public, anon, authenticated;
grant execute on function public.can_read_payroll() to public;
grant execute on function public.can_read_payroll() to authenticated;
revoke all on function public.cham_bu_cong(uuid,date,time without time zone,time without time zone,text) from public, anon, authenticated;
grant execute on function public.cham_bu_cong(uuid,date,time without time zone,time without time zone,text) to authenticated;
revoke all on function public.chan_ca_cong_nhat_chong_nhau() from public, anon, authenticated;
grant execute on function public.chan_ca_cong_nhat_chong_nhau() to public;
grant execute on function public.chan_ca_cong_nhat_chong_nhau() to anon;
grant execute on function public.chan_ca_cong_nhat_chong_nhau() to authenticated;
revoke all on function public.chan_cho_to_truong_roi_to() from public, anon, authenticated;
grant execute on function public.chan_cho_to_truong_roi_to() to public;
grant execute on function public.chan_cho_to_truong_roi_to() to anon;
grant execute on function public.chan_cho_to_truong_roi_to() to authenticated;
revoke all on function public.chan_mat_quyen_admin() from public, anon, authenticated;
grant execute on function public.chan_mat_quyen_admin() to public;
grant execute on function public.chan_mat_quyen_admin() to anon;
grant execute on function public.chan_mat_quyen_admin() to authenticated;
revoke all on function public.chan_to_truong_ngoai_to() from public, anon, authenticated;
grant execute on function public.chan_to_truong_ngoai_to() to public;
grant execute on function public.chan_to_truong_ngoai_to() to anon;
grant execute on function public.chan_to_truong_ngoai_to() to authenticated;
revoke all on function public.chan_tu_duyet_cong_to() from public, anon, authenticated;
grant execute on function public.chan_tu_duyet_cong_to() to public;
grant execute on function public.chan_tu_duyet_cong_to() to anon;
grant execute on function public.chan_tu_duyet_cong_to() to authenticated;
revoke all on function public.chot_ky_luong(uuid) from public, anon, authenticated;
grant execute on function public.chot_ky_luong(uuid) to authenticated;
revoke all on function public.chuc_danh_chinh_tai_ngay(uuid,date) from public, anon, authenticated;
grant execute on function public.chuc_danh_chinh_tai_ngay(uuid,date) to public;
grant execute on function public.chuc_danh_chinh_tai_ngay(uuid,date) to authenticated;
revoke all on function public.chuc_danh_cua_nhan_vien(uuid,date) from public, anon, authenticated;
grant execute on function public.chuc_danh_cua_nhan_vien(uuid,date) to public;
grant execute on function public.chuc_danh_cua_nhan_vien(uuid,date) to authenticated;
revoke all on function public.co_quyen_cua(uuid,text) from public, anon, authenticated;
grant execute on function public.co_quyen_cua(uuid,text) to authenticated;
revoke all on function public.co_quyen(text) from public, anon, authenticated;
grant execute on function public.co_quyen(text) to authenticated;
revoke all on function public.co_the_doc_bang_thanh_toan(uuid) from public, anon, authenticated;
grant execute on function public.co_the_doc_bang_thanh_toan(uuid) to public;
grant execute on function public.co_the_doc_bang_thanh_toan(uuid) to authenticated;
revoke all on function public.co_the_doc_chung_tu_theo_duong_dan(text) from public, anon, authenticated;
grant execute on function public.co_the_doc_chung_tu_theo_duong_dan(text) to authenticated;
revoke all on function public.co_the_doc_chung_tu(loai_chung_tu,uuid) from public, anon, authenticated;
grant execute on function public.co_the_doc_chung_tu(loai_chung_tu,uuid) to authenticated;
revoke all on function public.cong_ty_cua_toi() from public, anon, authenticated;
grant execute on function public.cong_ty_cua_toi() to public;
grant execute on function public.cong_ty_cua_toi() to authenticated;
revoke all on function public.current_app_role() from public, anon, authenticated;
grant execute on function public.current_app_role() to public;
grant execute on function public.current_app_role() to authenticated;
revoke all on function public.current_company_id() from public, anon, authenticated;
grant execute on function public.current_company_id() to public;
grant execute on function public.current_company_id() to anon;
grant execute on function public.current_company_id() to authenticated;
revoke all on function public.current_department_id() from public, anon, authenticated;
grant execute on function public.current_department_id() to public;
grant execute on function public.current_department_id() to authenticated;
revoke all on function public.current_employee_id() from public, anon, authenticated;
grant execute on function public.current_employee_id() to public;
grant execute on function public.current_employee_id() to authenticated;
revoke all on function public.danh_dau_da_tra(uuid) from public, anon, authenticated;
grant execute on function public.danh_dau_da_tra(uuid) to authenticated;
revoke all on function public.dat_cong_chuan_cho_ky() from public, anon, authenticated;
grant execute on function public.dat_cong_chuan_cho_ky() to public;
grant execute on function public.dat_cong_chuan_cho_ky() to anon;
grant execute on function public.dat_cong_chuan_cho_ky() to authenticated;
revoke all on function public.doi_chuc_danh_chinh(uuid,uuid,date,text) from public, anon, authenticated;
grant execute on function public.doi_chuc_danh_chinh(uuid,uuid,date,text) to authenticated;
revoke all on function public.ds_tai_khoan() from public, anon, authenticated;
grant execute on function public.ds_tai_khoan() to authenticated;
revoke all on function public.duoc_duyet_cong_to() from public, anon, authenticated;
grant execute on function public.duoc_duyet_cong_to() to authenticated;
revoke all on function public.duoc_ghi_anh_phien(uuid,uuid) from public, anon, authenticated;
grant execute on function public.duoc_ghi_anh_phien(uuid,uuid) to authenticated;
revoke all on function public.duoc_sua_chua_cong() from public, anon, authenticated;
grant execute on function public.duoc_sua_chua_cong() to authenticated;
revoke all on function public.ghi_chung_tu(loai_chung_tu,uuid,text,text,numeric,integer,integer,text,uuid) from public, anon, authenticated;
revoke all on function public.gio_ca_cong_nhat(uuid,boolean,boolean,boolean) from public, anon, authenticated;
grant execute on function public.gio_ca_cong_nhat(uuid,boolean,boolean,boolean) to authenticated;
revoke all on function public.gio_cong_nhat_tu_khoang(uuid,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone) from public, anon, authenticated;
grant execute on function public.gio_cong_nhat_tu_khoang(uuid,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone,time without time zone) to authenticated;
revoke all on function public.handle_new_auth_user() from public, anon, authenticated;
grant execute on function public.handle_new_auth_user() to public;
grant execute on function public.handle_new_auth_user() to anon;
grant execute on function public.handle_new_auth_user() to authenticated;
revoke all on function public.he_so_lam_them_hieu_luc(date) from public, anon, authenticated;
grant execute on function public.he_so_lam_them_hieu_luc(date) to authenticated;
revoke all on function public.is_hr_or_admin() from public, anon, authenticated;
grant execute on function public.is_hr_or_admin() to public;
grant execute on function public.is_hr_or_admin() to authenticated;
revoke all on function public.khoi_phuc_cham_cong(uuid) from public, anon, authenticated;
grant execute on function public.khoi_phuc_cham_cong(uuid) to authenticated;
revoke all on function public.khoi_phuc_nhan_su(uuid) from public, anon, authenticated;
grant execute on function public.khoi_phuc_nhan_su(uuid) to authenticated;
revoke all on function public.kiem_nguoi_cham_chinh_thuc() from public, anon, authenticated;
grant execute on function public.kiem_nguoi_cham_chinh_thuc() to public;
grant execute on function public.kiem_nguoi_cham_chinh_thuc() to anon;
grant execute on function public.kiem_nguoi_cham_chinh_thuc() to authenticated;
revoke all on function public.ky_luong_cua_ngay(uuid,date) from public, anon, authenticated;
grant execute on function public.ky_luong_cua_ngay(uuid,date) to authenticated;
revoke all on function public.la_nguoi_cham_cong_phien(uuid) from public, anon, authenticated;
grant execute on function public.la_nguoi_cham_cong_phien(uuid) to public;
grant execute on function public.la_nguoi_cham_cong_phien(uuid) to authenticated;
revoke all on function public.la_nguoi_cham_cong_to_txt(text) from public, anon, authenticated;
grant execute on function public.la_nguoi_cham_cong_to_txt(text) to public;
grant execute on function public.la_nguoi_cham_cong_to_txt(text) to authenticated;
revoke all on function public.la_nguoi_cham_cong_to(uuid) from public, anon, authenticated;
grant execute on function public.la_nguoi_cham_cong_to(uuid) to public;
grant execute on function public.la_nguoi_cham_cong_to(uuid) to authenticated;
revoke all on function public.la_nguoi_cham_cua_nhan_su(uuid) from public, anon, authenticated;
grant execute on function public.la_nguoi_cham_cua_nhan_su(uuid) to public;
grant execute on function public.la_nguoi_cham_cua_nhan_su(uuid) to authenticated;
revoke all on function public.la_nhan_cong_to_doi(uuid) from public, anon, authenticated;
grant execute on function public.la_nhan_cong_to_doi(uuid) to authenticated;
revoke all on function public.la_nhan_vien_chinh_thuc(uuid) from public, anon, authenticated;
grant execute on function public.la_nhan_vien_chinh_thuc(uuid) to public;
grant execute on function public.la_nhan_vien_chinh_thuc(uuid) to authenticated;
revoke all on function public.la_quan_ly_to_doi() from public, anon, authenticated;
grant execute on function public.la_quan_ly_to_doi() to public;
grant execute on function public.la_quan_ly_to_doi() to authenticated;
revoke all on function public.luong_bhxh_tai_ngay(uuid,date) from public, anon, authenticated;
grant execute on function public.luong_bhxh_tai_ngay(uuid,date) to public;
grant execute on function public.luong_bhxh_tai_ngay(uuid,date) to authenticated;
revoke all on function public.luong_chuc_danh_binh_quan(uuid,date,date) from public, anon, authenticated;
grant execute on function public.luong_chuc_danh_binh_quan(uuid,date,date) to public;
grant execute on function public.luong_chuc_danh_binh_quan(uuid,date,date) to authenticated;
revoke all on function public.luong_chuc_danh_tai_ngay(uuid,date) from public, anon, authenticated;
grant execute on function public.luong_chuc_danh_tai_ngay(uuid,date) to public;
grant execute on function public.luong_chuc_danh_tai_ngay(uuid,date) to authenticated;
revoke all on function public.mo_lai_phien_to(uuid,text) from public, anon, authenticated;
grant execute on function public.mo_lai_phien_to(uuid,text) to authenticated;
revoke all on function public.muc_luong_trong_ky(uuid,date,date) from public, anon, authenticated;
grant execute on function public.muc_luong_trong_ky(uuid,date,date) to public;
grant execute on function public.muc_luong_trong_ky(uuid,date,date) to authenticated;
revoke all on function public.phien_con_sua_duoc(uuid) from public, anon, authenticated;
grant execute on function public.phien_con_sua_duoc(uuid) to public;
grant execute on function public.phien_con_sua_duoc(uuid) to authenticated;
revoke all on function public.phu_cap_cua_nhan_vien(uuid,date,jsonb) from public, anon, authenticated;
grant execute on function public.phu_cap_cua_nhan_vien(uuid,date,jsonb) to public;
grant execute on function public.phu_cap_cua_nhan_vien(uuid,date,jsonb) to authenticated;
revoke all on function public.phu_cap_hop_dong_hop_le(jsonb) from public, anon, authenticated;
grant execute on function public.phu_cap_hop_dong_hop_le(jsonb) to public;
grant execute on function public.phu_cap_hop_dong_hop_le(jsonb) to anon;
grant execute on function public.phu_cap_hop_dong_hop_le(jsonb) to authenticated;
revoke all on function public.phut_giao_gio(time without time zone,time without time zone,time without time zone,time without time zone) from public, anon, authenticated;
grant execute on function public.phut_giao_gio(time without time zone,time without time zone,time without time zone,time without time zone) to public;
grant execute on function public.phut_giao_gio(time without time zone,time without time zone,time without time zone,time without time zone) to anon;
grant execute on function public.phut_giao_gio(time without time zone,time without time zone,time without time zone,time without time zone) to authenticated;
revoke all on function public.phut_giao_nhau(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone) from public, anon, authenticated;
grant execute on function public.phut_giao_nhau(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone) to public;
grant execute on function public.phut_giao_nhau(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone) to anon;
grant execute on function public.phut_giao_nhau(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone) to authenticated;
revoke all on function public.phut_trong_ngay(time without time zone,boolean) from public, anon, authenticated;
grant execute on function public.phut_trong_ngay(time without time zone,boolean) to public;
grant execute on function public.phut_trong_ngay(time without time zone,boolean) to anon;
grant execute on function public.phut_trong_ngay(time without time zone,boolean) to authenticated;
revoke all on function public.quyen_tu_tab(text[],boolean) from public, anon, authenticated;
grant execute on function public.quyen_tu_tab(text[],boolean) to public;
grant execute on function public.quyen_tu_tab(text[],boolean) to anon;
grant execute on function public.quyen_tu_tab(text[],boolean) to authenticated;
revoke all on function public.sinh_bang_thanh_toan_to(uuid,date,date) from public, anon, authenticated;
grant execute on function public.sinh_bang_thanh_toan_to(uuid,date,date) to authenticated;
revoke all on function public.sua_nhan_cong_to(uuid,text,text,numeric,numeric) from public, anon, authenticated;
grant execute on function public.sua_nhan_cong_to(uuid,text,text,numeric,numeric) to authenticated;
revoke all on function public.sua_tay_dong_thanh_toan_to(uuid,numeric,numeric,numeric,numeric,numeric,text) from public, anon, authenticated;
grant execute on function public.sua_tay_dong_thanh_toan_to(uuid,numeric,numeric,numeric,numeric,numeric,text) to authenticated;
revoke all on function public.tai_khoan_cua_toi() from public, anon, authenticated;
grant execute on function public.tai_khoan_cua_toi() to authenticated;
revoke all on function public.tao_to_doi(text,text,uuid,text) from public, anon, authenticated;
grant execute on function public.tao_to_doi(text,text,uuid,text) to authenticated;
revoke all on function public.tao_truy_linh(uuid,date,numeric,text,jsonb) from public, anon, authenticated;
grant execute on function public.tao_truy_linh(uuid,date,numeric,text,jsonb) to authenticated;
revoke all on function public.thac_mac_phieu_luong(uuid,text) from public, anon, authenticated;
grant execute on function public.thac_mac_phieu_luong(uuid,text) to authenticated;
revoke all on function public.them_nhan_cong_to(uuid,text,text,numeric,numeric,date) from public, anon, authenticated;
grant execute on function public.them_nhan_cong_to(uuid,text,text,numeric,numeric,date) to authenticated;
revoke all on function public.thue_tncn(numeric,date) from public, anon, authenticated;
revoke all on function public.thung_rac_cham_cong() from public, anon, authenticated;
grant execute on function public.thung_rac_cham_cong() to authenticated;
revoke all on function public.thung_rac_nhan_su() from public, anon, authenticated;
grant execute on function public.thung_rac_nhan_su() to authenticated;
revoke all on function public.tien_do_xac_nhan_ky(uuid) from public, anon, authenticated;
grant execute on function public.tien_do_xac_nhan_ky(uuid) to public;
grant execute on function public.tien_do_xac_nhan_ky(uuid) to anon;
grant execute on function public.tien_do_xac_nhan_ky(uuid) to authenticated;
revoke all on function public.tinh_cong_mot_ngay(date,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone,time without time zone,time without time zone,time without time zone,time without time zone) from public, anon, authenticated;
grant execute on function public.tinh_cong_mot_ngay(date,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone,time without time zone,time without time zone,time without time zone,time without time zone) to public;
grant execute on function public.tinh_cong_mot_ngay(date,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone,time without time zone,time without time zone,time without time zone,time without time zone) to anon;
grant execute on function public.tinh_cong_mot_ngay(date,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone,time without time zone,time without time zone,time without time zone,time without time zone) to authenticated;
revoke all on function public.tinh_gio_tu_ca() from public, anon, authenticated;
grant execute on function public.tinh_gio_tu_ca() to public;
grant execute on function public.tinh_gio_tu_ca() to anon;
grant execute on function public.tinh_gio_tu_ca() to authenticated;
revoke all on function public.tinh_luong_ky_cua_toi(uuid) from public, anon, authenticated;
grant execute on function public.tinh_luong_ky_cua_toi(uuid) to authenticated;
revoke all on function public.tinh_luong_ky(uuid) from public, anon, authenticated;
revoke all on function public.tong_hop_cong_ngay_cua_toi(date) from public, anon, authenticated;
grant execute on function public.tong_hop_cong_ngay_cua_toi(date) to authenticated;
revoke all on function public.tong_hop_cong_ngay(date) from public, anon, authenticated;
revoke all on function public.touch_updated_at() from public, anon, authenticated;
grant execute on function public.touch_updated_at() to public;
grant execute on function public.touch_updated_at() to anon;
grant execute on function public.touch_updated_at() to authenticated;
revoke all on function public.tu_dong_xac_nhan_phieu_qua_han(uuid) from public, anon, authenticated;
grant execute on function public.tu_dong_xac_nhan_phieu_qua_han(uuid) to authenticated;
revoke all on function public.xac_nhan_cham_cong_ngay(date,text) from public, anon, authenticated;
grant execute on function public.xac_nhan_cham_cong_ngay(date,text) to authenticated;
revoke all on function public.xac_nhan_phieu_luong(uuid) from public, anon, authenticated;
grant execute on function public.xac_nhan_phieu_luong(uuid) to authenticated;
revoke all on function public.xoa_cham_cong(uuid,text) from public, anon, authenticated;
grant execute on function public.xoa_cham_cong(uuid,text) to authenticated;
revoke all on function public.xoa_lan_cham_de_sua(uuid,text) from public, anon, authenticated;
grant execute on function public.xoa_lan_cham_de_sua(uuid,text) to authenticated;
revoke all on function public.xoa_nhan_su(uuid,text) from public, anon, authenticated;
grant execute on function public.xoa_nhan_su(uuid,text) to authenticated;

-- ---- Hàm: Tài chính ----
revoke all on function public.admin_huy_giao_dich(text,uuid,text) from public, anon, authenticated;
grant execute on function public.admin_huy_giao_dich(text,uuid,text) to public;
grant execute on function public.admin_huy_giao_dich(text,uuid,text) to authenticated;
revoke all on function public.admin_khoi_phuc_giao_dich(uuid) from public, anon, authenticated;
grant execute on function public.admin_khoi_phuc_giao_dich(uuid) to public;
grant execute on function public.admin_khoi_phuc_giao_dich(uuid) to authenticated;
revoke all on function public.admin_kiem_xoa_nhan_vien(uuid) from public, anon, authenticated;
grant execute on function public.admin_kiem_xoa_nhan_vien(uuid) to authenticated;
revoke all on function public.admin_sua_giao_dich(text,uuid,jsonb,text) from public, anon, authenticated;
grant execute on function public.admin_sua_giao_dich(text,uuid,jsonb,text) to public;
grant execute on function public.admin_sua_giao_dich(text,uuid,jsonb,text) to authenticated;
revoke all on function public.admin_xoa_giao_dich(text,uuid,text) from public, anon, authenticated;
grant execute on function public.admin_xoa_giao_dich(text,uuid,text) to public;
grant execute on function public.admin_xoa_giao_dich(text,uuid,text) to authenticated;
revoke all on function public.admin_xoa_nhan_vien(uuid,text) from public, anon, authenticated;
grant execute on function public.admin_xoa_nhan_vien(uuid,text) to authenticated;
revoke all on function public.chu_tich_duyet_dot_qua_bot(uuid,uuid) from public, anon, authenticated;
revoke all on function public.chu_tich_duyet_dot(uuid,text) from public, anon, authenticated;
grant execute on function public.chu_tich_duyet_dot(uuid,text) to authenticated;
revoke all on function public.chu_tich_tu_choi_dot(uuid,text) from public, anon, authenticated;
grant execute on function public.chu_tich_tu_choi_dot(uuid,text) to authenticated;
revoke all on function public.dinh_chung_tu_de_nghi(uuid,jsonb) from public, anon, authenticated;
grant execute on function public.dinh_chung_tu_de_nghi(uuid,jsonb) to authenticated;
revoke all on function public.dong_dot(uuid,text) from public, anon, authenticated;
grant execute on function public.dong_dot(uuid,text) to authenticated;
revoke all on function public.gui_duyet_de_nghi(uuid,text) from public, anon, authenticated;
grant execute on function public.gui_duyet_de_nghi(uuid,text) to authenticated;
revoke all on function public.huy_de_nghi(uuid,text) from public, anon, authenticated;
grant execute on function public.huy_de_nghi(uuid,text) to authenticated;
revoke all on function public.huy_nop_lai_tien_thua(uuid,text) from public, anon, authenticated;
grant execute on function public.huy_nop_lai_tien_thua(uuid,text) to authenticated;
revoke all on function public.kiem_nhap_quy_trung(uuid,numeric,date) from public, anon, authenticated;
grant execute on function public.kiem_nhap_quy_trung(uuid,numeric,date) to authenticated;
revoke all on function public.ktt_tao_dot_duyet(uuid,jsonb,text) from public, anon, authenticated;
grant execute on function public.ktt_tao_dot_duyet(uuid,jsonb,text) to authenticated;
revoke all on function public.ktt_tao_dot_duyet(uuid,uuid[],text) from public, anon, authenticated;
grant execute on function public.ktt_tao_dot_duyet(uuid,uuid[],text) to authenticated;
revoke all on function public.ktt_tra_ve_de_nghi(uuid,text) from public, anon, authenticated;
grant execute on function public.ktt_tra_ve_de_nghi(uuid,text) to authenticated;
revoke all on function public.ktt_tu_choi_muc(uuid,text) from public, anon, authenticated;
grant execute on function public.ktt_tu_choi_muc(uuid,text) to authenticated;
revoke all on function public.luu_ton_dau_ky(uuid,uuid,tien_te,date) from public, anon, authenticated;
grant execute on function public.luu_ton_dau_ky(uuid,uuid,tien_te,date) to authenticated;
revoke all on function private.bat_buoc_vai_tro(text,text) from public, anon, authenticated;
revoke all on function private.bi_siet_theo_nguon_tien() from public, anon, authenticated;
grant execute on function private.bi_siet_theo_nguon_tien() to authenticated;
revoke all on function private.bu_cong_no_am_cho_nguoi(uuid,uuid,uuid,numeric,date,uuid,text) from public, anon, authenticated;
revoke all on function private.but_toan_nhap_quy_trung(uuid,numeric,date) from public, anon, authenticated;
grant execute on function private.but_toan_nhap_quy_trung(uuid,numeric,date) to authenticated;
revoke all on function private.chan_nguon_khong_duoc_phan_quyen() from public, anon, authenticated;
revoke all on function private.chan_phieu_thu_trung_nhap_quy() from public, anon, authenticated;
revoke all on function private.chan_sua_khoan_muc_he_thong() from public, anon, authenticated;
grant execute on function private.chan_sua_khoan_muc_he_thong() to public;
revoke all on function private.chan_sua_nhat_ky() from public, anon, authenticated;
grant execute on function private.chan_sua_nhat_ky() to public;
revoke all on function private.chan_sua_so_quy() from public, anon, authenticated;
grant execute on function private.chan_sua_so_quy() to public;
revoke all on function private.co_mot_trong_vai_tro(text[]) from public, anon, authenticated;
grant execute on function private.co_mot_trong_vai_tro(text[]) to authenticated;
revoke all on function private.co_tab(text) from public, anon, authenticated;
grant execute on function private.co_tab(text) to authenticated;
revoke all on function private.co_vai_tro(text) from public, anon, authenticated;
grant execute on function private.co_vai_tro(text) to authenticated;
revoke all on function private.con_phai_chi_that(uuid) from public, anon, authenticated;
grant execute on function private.con_phai_chi_that(uuid) to authenticated;
revoke all on function private.dong_quyet_toan_da_can_doi(uuid,uuid) from public, anon, authenticated;
grant execute on function private.dong_quyet_toan_da_can_doi(uuid,uuid) to authenticated;
revoke all on function private.duoc_sua_danh_muc() from public, anon, authenticated;
grant execute on function private.duoc_sua_danh_muc() to authenticated;
revoke all on function private.duoc_xem_de_nghi(uuid) from public, anon, authenticated;
grant execute on function private.duoc_xem_de_nghi(uuid) to authenticated;
revoke all on function private.duoc_xem_file(text) from public, anon, authenticated;
grant execute on function private.duoc_xem_file(text) to authenticated;
revoke all on function private.duoc_xem_nguon_tien(uuid,uuid) from public, anon, authenticated;
grant execute on function private.duoc_xem_nguon_tien(uuid,uuid) to authenticated;
revoke all on function private.file_da_gan_chung_tu(text) from public, anon, authenticated;
grant execute on function private.file_da_gan_chung_tu(text) to authenticated;
revoke all on function private.ghi_chi_quy_cong_truong(uuid,uuid) from public, anon, authenticated;
revoke all on function private.ghi_nhat_ky(text,uuid,text,jsonb,jsonb) from public, anon, authenticated;
revoke all on function private.han_muc_tam_ung_da_duyet(uuid) from public, anon, authenticated;
grant execute on function private.han_muc_tam_ung_da_duyet(uuid) to authenticated;
revoke all on function private.la_nguoi_quan_ly_tai_chinh() from public, anon, authenticated;
grant execute on function private.la_nguoi_quan_ly_tai_chinh() to authenticated;
revoke all on function private.ma_danh_muc_tiep_theo(text,text) from public, anon, authenticated;
revoke all on function private.mo_ta_giao_dich(text,jsonb) from public, anon, authenticated;
grant execute on function private.mo_ta_giao_dich(text,jsonb) to public;
revoke all on function private.nhan_vien_hien_tai() from public, anon, authenticated;
grant execute on function private.nhan_vien_hien_tai() to authenticated;
revoke all on function private.quy_cua_nguoi_nhan_ung(uuid) from public, anon, authenticated;
grant execute on function private.quy_cua_nguoi_nhan_ung(uuid) to authenticated;
revoke all on function private.sinh_so_de_nghi(text,text,integer) from public, anon, authenticated;
revoke all on function private.snapshot_va_xoa_giao_dich(text,uuid) from public, anon, authenticated;
revoke all on function private.so_du_han_muc_quyet_toan(uuid) from public, anon, authenticated;
grant execute on function private.so_du_han_muc_quyet_toan(uuid) to authenticated;
revoke all on function private.so_du_nguon_tien(uuid,uuid) from public, anon, authenticated;
revoke all on function private.sua_so_tien_phieu_chi(uuid,jsonb) from public, anon, authenticated;
revoke all on function private.tg_ma_danh_muc() from public, anon, authenticated;
grant execute on function private.tg_ma_danh_muc() to public;
revoke all on function private.tg_xet_lai_quyet_toan_sau_tra_tien() from public, anon, authenticated;
grant execute on function private.tg_xet_lai_quyet_toan_sau_tra_tien() to public;
revoke all on function private.tra_bu_toi_da(uuid) from public, anon, authenticated;
grant execute on function private.tra_bu_toi_da(uuid) to authenticated;
revoke all on function private.tu_dong_cap_nhat_updated_at() from public, anon, authenticated;
grant execute on function private.tu_dong_cap_nhat_updated_at() to public;
revoke all on function private.vuong_mac_nhan_vien(uuid) from public, anon, authenticated;
revoke all on function public.tao_chuyen_quy(jsonb) from public, anon, authenticated;
grant execute on function public.tao_chuyen_quy(jsonb) to authenticated;
revoke all on function public.tao_nop_lai_tien_thua(uuid,numeric,date,uuid,uuid) from public, anon, authenticated;
grant execute on function public.tao_nop_lai_tien_thua(uuid,numeric,date,uuid,uuid) to authenticated;
revoke all on function public.tao_phieu_thu(jsonb) from public, anon, authenticated;
grant execute on function public.tao_phieu_thu(jsonb) to authenticated;
revoke all on function public.tao_sua_de_nghi_nhap(jsonb) from public, anon, authenticated;
grant execute on function public.tao_sua_de_nghi_nhap(jsonb) to authenticated;
revoke all on function public.tra_tam_ung_cap_tru(uuid,jsonb,jsonb,jsonb,date,uuid,uuid) from public, anon, authenticated;
grant execute on function public.tra_tam_ung_cap_tru(uuid,jsonb,jsonb,jsonb,date,uuid,uuid) to public;
grant execute on function public.tra_tam_ung_cap_tru(uuid,jsonb,jsonb,jsonb,date,uuid,uuid) to authenticated;
revoke all on function public.tra_tien_dot(uuid,jsonb,jsonb,date,uuid,uuid,boolean) from public, anon, authenticated;
grant execute on function public.tra_tien_dot(uuid,jsonb,jsonb,date,uuid,uuid,boolean) to authenticated;
revoke all on function public.xac_nhan_nop_lai_tien_thua(uuid) from public, anon, authenticated;
grant execute on function public.xac_nhan_nop_lai_tien_thua(uuid) to authenticated;
revoke all on function public.xac_nhan_phieu_thu(uuid) from public, anon, authenticated;
grant execute on function public.xac_nhan_phieu_thu(uuid) to authenticated;
revoke all on function public.xoa_chung_tu_de_nghi(uuid) from public, anon, authenticated;
grant execute on function public.xoa_chung_tu_de_nghi(uuid) to authenticated;

-- ---- Schema private (Tài chính) ----
revoke all on schema private from public, anon, authenticated;
grant USAGE on schema private to authenticated;
